env: dev
wp:
  production:
    db: prod_wp
    user: root
    password:
    host: localhost
    prefix: prod_wp_
  pre_production:
    db: pre_wp
    user: root
    password:
    host: localhost
    prefix: pre_wp_
  dev:
    url: 'http://wordpress.org/latest.tar.gz'
    db: wp
    user: root
    password:
    host: localhost
    prefix: wp_
  dir: wp
db:
  production:
    db: prod_app
    user: root
    password:
    host: localhost
    prefix: prod_app_
  pre_production:
    db: pre_app
    user: root
    password:
    host: localhost
    prefix: pre_app_
  dev:
    db: app
    user: root
    password:
    host: localhost
    prefix: app_
