env: dev
wp:
  dir: wp
db:
  production:
    db: prod_app
    user: username
    password: ahardpass
    host: localhost
    prefix: prod_app_
  pre_production:
    db: pre_app
    user: username
    password: ahardpass
    host: localhost
    prefix: pre_app_
  dev:
    db: app
    user: username
    password: ahardpass
    prefix: app_
